name: oyimg
channels:
  - conda-forge
  - anaconda
  - nvidia 
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip
  - scipy
  - tifffile
  - tqdm
  - opencv
  - jupyter
  - matplotlib
  - pandas
  - scikit-image
  - scikit-learn
  - numba
  - dill
  - cmake
  - nd2reader
  - napari=0.4.11
  - pyfftw
  - h5py
  - cupy
  - pip:
    - cellpose
    - lap
    - zernike
    - -f "https://download.pytorch.org/whl/torch_stable.html"
    - torch==1.8.1+cu111
    - torchvision==0.9.1+cu111
    - torchaudio==0.8.1
    - -e .

