name: oyproc
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - scipy
  - tifffile
  - tqdm
  - opencv
  - jupyter
  - matplotlib
  - pandas
  - scikit-image
  - scikit-learn
  - numba
  - dill
  - cmake
  - pip:
    - qtpy
    - pyqt5
    - cellpose
    - lap
    - napari
prefix: /home/alon/.conda/envs/oyproc