name: oyproc
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - alabaster=0.7.12=py_0
  - argon2-cffi=20.1.0=py38h1e0a361_1
  - asciitree=0.3.3=py_2
  - async_generator=1.10=py_0
  - attrs=20.2.0=pyh9f0ad1d_0
  - babel=2.8.0=py_0
  - backcall=0.2.0=py_0
  - blas=2.17=openblas
  - bleach=3.2.1=pyh9f0ad1d_0
  - blosc=1.20.1=he1b5a44_0
  - bokeh=2.2.1=py38h32f6830_0
  - brotli=1.0.9=he1b5a44_0
  - brotlipy=0.7.0=py38h1e0a361_1000
  - brunsli=0.1=he1b5a44_0
  - bzip2=1.0.8=h516909a_3
  - ca-certificates=2020.6.20=hecda079_0
  - cachey=0.2.1=pyh9f0ad1d_0
  - cairo=1.16.0=h3fc0475_1005
  - certifi=2020.6.20=py38h32f6830_0
  - cffi=1.14.3=py38h5bae8af_0
  - chardet=3.0.4=py38h32f6830_1006
  - charls=2.1.0=he1b5a44_2
  - click=7.1.2=pyh9f0ad1d_0
  - cloudpickle=1.6.0=py_0
  - cryptography=3.1=py38h766eaa4_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py38h7b6447c_0
  - dask=2.26.0=py_0
  - dask-core=2.26.0=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - dill=0.3.2=py_0
  - distributed=2.26.0=py38h32f6830_0
  - docutils=0.16=py38h32f6830_1
  - entrypoints=0.3=py38h32f6830_1001
  - expat=2.2.9=he1b5a44_2
  - fasteners=0.14.1=py_3
  - ffmpeg=4.3.1=h167e202_0
  - fftw=3.3.8=nompi_h7f3a6c3_1111
  - fontconfig=2.13.1=h1056068_1002
  - freetype=2.10.2=he06d7ca_0
  - freetype-py=2.2.0=pyh9f0ad1d_0
  - fsspec=0.8.2=py_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_2
  - glib=2.66.0=h0dae87d_0
  - gmp=6.2.0=he1b5a44_2
  - gnutls=3.6.13=h79a8f9a_0
  - graphite2=1.3.13=he1b5a44_1001
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - harfbuzz=2.7.2=hee91db6_0
  - hdf5=1.10.6=nompi_h3c11f04_101
  - heapdict=1.0.1=py_0
  - icu=67.1=he1b5a44_0
  - idna=2.10=pyh9f0ad1d_0
  - imagecodecs=2020.5.30=py38h36e1e94_2
  - imageio=2.9.0=py_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=1.7.0=py38h32f6830_0
  - importlib_metadata=1.7.0=0
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipympl=0.5.8=pyh9f0ad1d_0
  - ipython=7.18.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - jasper=1.900.1=h07fcdf6_1006
  - jedi=0.17.2=py38_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.16.0=py_0
  - jpeg=9d=h516909a_0
  - jsonschema=3.2.0=py38h32f6830_1
  - jupyter_client=6.1.6=py_0
  - jupyter_core=4.6.3=py38_0
  - jupyterlab_pygments=0.1.1=pyh9f0ad1d_0
  - jxrlib=1.1=h516909a_2
  - kiwisolver=1.2.0=py38hbf85e49_0
  - krb5=1.17.1=hfafb76e_3
  - lame=3.100=h14c3975_1001
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - lerc=2.2=he1b5a44_0
  - libaec=1.0.4=he1b5a44_1
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libclang=10.0.1=default_hde54327_1
  - libedit=3.1.20191231=h14c3975_1
  - libevent=2.1.10=hcdb4288_2
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.16=h516909a_0
  - liblapack=3.8.0=17_openblas
  - liblapacke=3.8.0=17_openblas
  - libllvm10=10.0.1=hbcb73fb_5
  - libopenblas=0.3.10=h5a2b251_0
  - libopencv=4.4.0=py38_2
  - libpng=1.6.37=hed695b0_2
  - libpq=12.3=h5513abc_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.39.0=h516909a_0
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=h68273f3_2
  - libxslt=1.1.33=h572872d_1
  - libzopfli=1.0.3=he1b5a44_0
  - llvm-openmp=10.0.1=hc9558a2_0
  - llvmlite=0.34.0=py38h269e1b5_4
  - locket=0.2.0=py_2
  - lz4-c=1.9.2=he1b5a44_3
  - markupsafe=1.1.1=py38h1e0a361_1
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py38h91b0d89_0
  - mistune=0.8.4=py38h1e0a361_1001
  - monotonic=1.5=py_0
  - msgpack-python=1.0.0=py38hbf85e49_1
  - mysql-common=8.0.21=2
  - mysql-libs=8.0.21=hf3661c5_2
  - napari-plugin-engine=0.1.8=py38h32f6830_0
  - nbclient=0.5.0=py_0
  - nbconvert=6.0.5=py38h32f6830_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.0=py_1
  - nettle=3.4.1=h1bed415_1002
  - networkx=2.5=py_0
  - nodejs=14.11.0=h568c755_0
  - notebook=6.1.4=py38h32f6830_0
  - nspr=4.28=he1b5a44_0
  - nss=3.56=he751ad9_0
  - numba=0.51.2=py38h0573a6f_1
  - numcodecs=0.7.2=py38h950e882_0
  - numpydoc=1.1.0=pyh9f0ad1d_0
  - olefile=0.46=py_0
  - opencv=4.4.0=py38_2
  - openh264=2.1.1=h8b12597_0
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1g=h516909a_1
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.2=py38h950e882_0
  - pandoc=2.10.1=h516909a_0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.0=py_0
  - partd=1.1.0=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.2.0=py38h9776b28_1
  - pip=20.2.2=py38_0
  - pixman=0.38.0=h516909a_1003
  - pluggy=0.13.1=py38h32f6830_2
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.7=py_0
  - psutil=5.7.2=py38h1e0a361_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py38_0
  - py-opencv=4.4.0=py38h23f93f0_2
  - pycparser=2.20=pyh9f0ad1d_2
  - pyfftw=0.12.0=py38h2c0d127_1
  - pygments=2.6.1=py_0
  - pyopengl=3.1.5=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38ha8c2ead_3
  - pyrsistent=0.17.3=py38h1e0a361_0
  - pyside2=5.13.2=py38hbee1fde_2
  - pysocks=1.7.1=py38h32f6830_1
  - python=3.8.3=cpython_he5300dc_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=pyh9f0ad1d_0
  - pywavelets=1.1.1=py38h7b6447c_0
  - pyyaml=5.3.1=py38h7b6447c_1
  - pyzmq=19.0.1=py38he6710b0_1
  - qt=5.12.9=h1f2b2cb_0
  - qtconsole=4.7.7=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=pyh9f0ad1d_0
  - scikit-image=0.16.2=py38h0573a6f_0
  - scikit-learn=0.23.2=py38h0573a6f_0
  - scipy=1.5.2=py38habc2bb6_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38_0
  - six=1.15.0=py_0
  - snappy=1.1.8=he1b5a44_3
  - snowballstemmer=2.0.0=py_0
  - sortedcontainers=2.2.2=pyh9f0ad1d_0
  - sphinx=3.2.1=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.33.0=h62c20be_0
  - tblib=1.6.0=py_0
  - terminado=0.9.1=py38h32f6830_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2020.9.3=py_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py38h7b6447c_1
  - tqdm=4.49.0=pyh9f0ad1d_0
  - traitlets=4.3.3=py38_0
  - typing_extensions=3.7.4.2=py_0
  - urllib3=1.25.10=py_0
  - vispy=0.6.4=py38ha0d6bf3_1
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=py_0
  - widgetsnbextension=3.5.1=py38h32f6830_1
  - wrapt=1.12.1=py38h1e0a361_1
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zarr=2.4.0=py_0
  - zeromq=4.3.2=he6710b0_3
  - zfp=0.5.5=he1b5a44_1
  - zict=2.0.0=py_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - appdirs==1.4.4
    - cachetools==4.1.1
    - cellpose==0.0.3.1
    - google-api-core==1.22.2
    - google-auth==1.21.2
    - google-cloud-core==1.4.1
    - google-cloud-storage==1.31.0
    - google-crc32c==1.0.0
    - google-resumable-media==1.0.0
    - googleapis-common-protos==1.52.0
    - json5==0.9.5
    - jupyterlab==2.2.8
    - jupyterlab-server==1.2.0
    - lap==0.4.0
    - mxnet==1.7.0.post1
    - napari-svg==0.1.4
    - natsort==7.0.1
    - numpy==1.19.2
    - opencv-python-headless==4.4.0.42
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtgraph==0.11.0rc0
    - pyqtwebengine==5.12.1
    - python-graphviz==0.8.4
    - rsa==4.6
prefix: /home/alon/.conda/envs/oyproc

